### ISSUE TITLE
In the absence of a startup.jl

### ISSUE THREAD

**Issue by francescoalemanno** [TsurHerman/Fezzik#1]
```
julia> using Fezzik
[ Info: Precompiling Fezzik [5c3170aa-382f-11e9-07a5-b732e1ee027c]


julia> 

julia> Fezzik.auto_trace()
ERROR: SystemError: opening file "/home/francesco/.julia/config/startup.jl"
```
After making the config directory and the file, this error disappeared.
Thankyou for this package, look forward to see it published

**Comment by TsurHerman** [comment]
fixed on master.

> look forward to see it published

I don't see any specific reason to register this package in the general repository

**Comment by francescoalemanno** [comment]
Alright!
