### ISSUE TITLE
Where' s the output

### ISSUE THREAD

**Issue by xgdgsc** [TsurHerman/Fezzik#2]
Thanks. I' m new to julia and bothered by its slow package loading time. I' m wondering what' s the output of this package. Where is this sysimg that is built? How to use to see how much speed improvements I could get?

**Comment by TsurHerman** [comment]
The output of Fezzik is a new sysimg , Fezzik attempts to replace the old one with the new one for you.

To measure the effects:

run a script file and measure how much time it took you from start to end.

then install Fezzik
one time setup:
`Fezzik.auto_trace(true)`

exit julia , re-enter and run your script again,Fezzik will trace the compiler activity.
exit julia, re-enter and run `Fezzik.brute_build_julia` , if on windows then follow the instructions at the end of the process to complete the process of replacing the old sysimg with the new one.

run a script file and measure how much time it took you from start to end.

Its all in the README.

**Comment by xgdgsc** [comment]
If I exit julia after run my script, then call `brute_build_julia` in the new session. It would show various errors regarding not finding my module. Do I have to put my package under `.julia` ? If I don' t exit julia after run my script and call `brute_build_julia`, it would run OK.

**Comment by TsurHerman** [comment]
It finds modules that are part of the system manifest or project I am not sure about the terminology.

what do you see when you do `Pkg.status()` and what modules Fezzik is not finding? 
you probably don't want to compile the module that you are actively developing.

**Comment by xgdgsc** [comment]
I kind of finished developing my module and want to speed it up, would it help putting it in `.julia`?

**Comment by TsurHerman** [comment]
try 
`Pkg.activate();Pkg.add("/path/to/git/repo/containng/module");
`

**Comment by xgdgsc** [comment]
Thanks.
