### ISSUE TITLE
Why `using Makie; lines(rand(5));` using sysimage generated from precompiles is about 5 times slower than `compile_incremental(:Makie, :AbstractPlotting)`?

### ISSUE THREAD

**Issue by KestutisMa** [TsurHerman/Fezzik#4]
`Makie.lines(rand(5));` is about 5 times slower after `brute_build_julia()` than `PackageCompiler.compile_incremental(:Makie, :AbstractPlotting)`. But `s = Scene()` is fast.
 Why could be that?
 Maybe something is not precompiled when calling Makie.lines()?

**Comment by TsurHerman** [comment]
If I remember correctly you have blacklisted “AbstractPlotting” , maybe whitelist it and try again? 


Fezzik is not meant to be optimal. It’s purpose is to be extremely simple to use and to allow you to actually use Julia and the eco-system of it without suffering too much from time to first ..you know.

**Comment by KestutisMa** [comment]
I have no packages blacklisted, with modified gf.c and codegen.c segfaults are gone during sysimages generation of Makie, Blink and Interact. It is interesting why such difference could appear, is seems that some functions are still compiled JIT. I am interested in technical side.

**Comment by TsurHerman** [comment]
> I am interested in technical side.

Ok I see, my theory is that some function goes "stale" when you add other functions to the global method table...(related maybe to the assertions?) and so they need to be recompiled again.

For my use case, I build a sysimg 10-15 times (working in one window and building in the other)
and only after a while I see the number of new statements to precompile drop to below 10

you should check out also the precomp.jl file and the traces directory to see which functions are being compiled

**Comment by KestutisMa** [comment]
I tried with and without assertions, same result (speedup is notable but still lesser).
1) Maybe some functions are not precompiled using `using Makie; lines(rand(5));`  but compiled when compile_incremental is using Makie runtests.jl file for snooping (default PakageCompiler behavior)? I tried to launch julia with --compile=all flag, but I saw parsing error while tired run brute_build_julia().
2) I ran brute_build_julia() second and third time and Fezzik genereted same precompiles, so maybe you are right about "stale" functions. But then why compile_incremental(:Makie, :AbstractPlotting) is compiling with greater speedup? maybe in that case not all functions are precompiled in that way that make them get "stale"?

Also, I tied run julia with --trace-compile flag (as mentioned in https://nextjournal.com/sdanisch/packagecompiler-talk) and replace Fezzik traces file with generated precompile file and I got same results as using Fezzik alone.

**Comment by KestutisMa** [comment]
Found one difference in how PackageCompiler generates precompiles from snooping, it's `compile=all` option:

https://github.com/JuliaLang/PackageCompiler.jl/blob/a403d8f3c69870e24cd41cc746bef4e926c5b055/src/snooping.jl#L32

Perhaps that could be cause.

**Comment by TsurHerman** [comment]
try with the newest version of Fezzik, see if it is resolved

**Comment by KestutisMa** [comment]
Thanks for update, but after compiling sysimage `Makie.lines(rand(5))` was same speed as with previous Fezzik version. I also tried provide Fezzik traces generated by `julia --compile=all -O0 -g0 --trace-compile=traces.jl myscript.jl`, there were no parsing errors this time, but `Makie.lines(rand(5))` speed was the same.

I also posted here: https://discourse.julialang.org/t/why-using-makie-lines-rand-5-using-sysimage-generated-from-precompiles-is-about-5-times-slower-than-compile-incremental-makie-abstractplotting/27808
It would be nice to know why this  happens.

Only few errors (but I don't think that this could effect Makie):
```
compiling line 146
┌ Info: UndefVarError(:WebIOServer)
│   LINE = 146
└ @ Main.##anon_module#377 /home/kest/.julia/packages/Fezzik/wdHmF/precomp.jl:149
compiling line 801
┌ Info: UndefVarError(Symbol("##96#97"))
│   LINE = 801
└ @ Main.##anon_module#377 /home/kest/.julia/packages/Fezzik/wdHmF/precomp.jl:804
compiling line 911
```

**Comment by KestutisMa** [comment]
Maybe this could fix this https://github.com/JuliaLang/julia/pull/33006

**Comment by TsurHerman** [comment]
We will see when it is merged

**Comment by TsurHerman** [comment]
@KestutisMa do you have any update on this?
