### ISSUE TITLE
Allow cpu_target to be set in high-level API

### ISSUE THREAD

**Issue by mdpetters** [TsurHerman/Fezzik#6]
I updated to Julia 1.4.0, which broke my deployed docker container with a compiled sys_image. After tracing the error I found the following issue

https://github.com/JuliaLang/PackageCompilerX.jl/issues/106

which I crudely resolved by patching the following line in bootstrap.jl

```julia
PackageCompiler.create_sysimage(precompile_execution_file = file , replace_default = true; cpu_target="generic")
```

It would be nice addition if the cpu_target could be specified through an optional keyword at the high-level API via

```julia
Fezzik.brute_build_julia(;cpu_target = ...)
```

**Comment by TsurHerman** [comment]
Can you issue a PR?
